---
id: faq
title: Troubleshooting
sidebar_label: Troubleshooting
---

import {
  HighlightWithText,
  HighlightWithCode,
} from '/src/components/Highlights'

import { DocsHeader } from '/src/components/Layout/DocsHeader'

<DocsHeader
  title="Sentry Troubleshooting"
  description="Sentry 运维问题及解决方案记录。"
  github="https://github.com/getsentry/sentry"
  tags={['Troubleshooting']}
  links={[
    {
      label: 'memcached client',
      link: 'https://www.sinacloud.com/doc/_static/memcache.html#Client',
    },
    {
      label: 'memcahed',
      link: 'https://memcached.org/',
    },
  ]}
/>

<!-- -->

## In Production

### 信息被 `[Filtered]` 占位

在查看错误字段时，发现信息被 `[Filtered]` 占位，并展示 `Replaced because PII rule "@xxxxxx:filter"`

是由于 sentry 匹配到敏感信息，并对其进行处理。**请确认该信息是否有能够展示！**

用户可以配置 `setting > Security & Privacy > Safe Feilds` 来放开指定敏感字段

## 无法定位到源码(结合 sourceMap)

:::note

首先通过 `sentry-cli sourcemaps explain <event_id>` 来排查 sourcemaps 文件匹配原因

:::

当出现无法定位 sourceMap 的问题时，我们首先需要确认用户的匹配路径，即：

1. 将源文件和 sourceMap 文件上传至平台，在文件系统内寻找 sourceMap 文件进行匹配；
2. 开启 `Allow JavaScript Source Fetching` 开关，由 Sentry 去线上寻找 sourceMap 文件进行匹配；

针对以上两点，我们需要从以下方面来进行排查：

- SDK 内是否配置 `release`，并配置对应版本，可以在平台内进行验证
- 是否上传 SourceMap 文件到指定的 release 版本内，可以在平台内 `Setting > Source Maps` 模块进行验证，可以查看是否有上传 Artifacts，能够在指定 release 内找到指定 .map 文件
- 查看源文件内，`sourceMappingURL` 是否被改写（系统会通过该字段来匹配 source map 文件），一些 CNDs 会更加优化而对静态文件进行处理，比如去掉文件内注释等
- 确保 SDK 内 `dist` 配置与上传 SourceMap 时配置一致。可以在 Issues 内检查是否存在 `dist` 标签来验证是否在 SDK 配置了该字段，而在 SourceMap 内可以检查右下角是否有一个小椭圆来验证
- 检查路径（文件名）是否匹配，如果路径中存在动态值，可以使用 `rewriteFrames` 来进行处理
- 确保 `artifacts` 在错误发生之前下载完成
- 文件是否太大/或者请求文件超时，导致无法写到缓存

## Remote file too large for caching

针对此问题，重点研究 Sentry 的缓存策略，相关配置如下：

1. 请求文件超时或者文件大小超过 `settings.SENTRY_SOURCE_FETCH_MAX_SIZE` 限制
2. `setting.SENTRY_CACHE_MAX_VALUE_SIZE` 被重新设置导致缓存受限
3. memcached 服务的 `item_size_max` 限制
4. memcached client 的配置 `SERVER_MAX_VALUE_LENGTH` 限制

Sentry 在拉取回文件之后，会通过 [memcached client](https://www.sinacloud.com/doc/_static/memcache.html#Client) 立即缓存到 [memcached](https://memcached.org/) 内，之后会通过 `cache.get` 尝试获取刚刚的缓存值，如果没有获取到，则会抛出异常 `EventError.TOO_LARGE_FOR_CACHE`。

因此当出现 `Remote file too large for caching` 的问题时，我们排障思路是确认**拉取文件过程**和**各个环节的缓存阈值**是否健康。

### 拉取文件

<HighlightWithText text="processor.py fetch_file()" />{' '}

```python
#...snippet
with metrics.timer("sourcemaps.fetch"):
    result = http.fetch_file(url, headers=headers, verify_ssl=verify_ssl)
    z_body = zlib.compress(result.body)
    cache.set(
        cache_key,
        (url, result.headers, z_body, result.status, result.encoding),
        get_max_age(result.headers),
    )

    if cache.get(cache_key) is None:
        error = {
            "type": EventError.TOO_LARGE_FOR_CACHE,
            "url": http.expose_url(url),
        }
        http.lock_domain(url, error=error)
        raise http.CannotFetch(error)
#...snippet
```

Sentry 认为导致 `cache.set` 失败的唯一的原因就是文件太大，因此直接抛出 `TOO_LARGE_FOR_CACHE` 的异常。

在拉取文件时，Sentry 调用 `http.fetch_file()` 方法，我们一探端倪。

<HighlightWithText text="http.py fetch_file()" />{' '}

```python
#...snippet
cl = 0
if response.status_code == 200:
    for chunk in response.iter_content(16 * 1024):
        if time.time() - start > settings.SENTRY_SOURCE_FETCH_TIMEOUT:
            raise Timeout()
        outfile.write(chunk)
        cl += len(chunk)
        if cl > settings.SENTRY_SOURCE_FETCH_MAX_SIZE:
            raise OverflowError()

except Exception as exc:
  #...
  elif isinstance(exc, OverflowError):
      error = {
          "type": EventError.FETCH_TOO_LARGE,
          # We want size in megabytes to format nicely
          "max_size": float(settings.SENTRY_SOURCE_FETCH_MAX_SIZE) / 1024 / 1024,
      }
#...snippet
```

Sentry 在确认 response status code 为 200 之后，会尝试去以 chunk 的形式读取返回内容。此时，会计算返回值 size，当其总和大于 `setting.SENTRY_SOURCE_FETCH_MAX_SIZE` 时，抛出异常。

在 `server.py` 配置中，观察其默认配置发现超过 40M 才会导致错误，而线上的实际表现是当文件超过 1M 时就已经抛出异常了：

```python
# Timeout (in seconds) for fetching remote source files (e.g. JS)
SENTRY_SOURCE_FETCH_TIMEOUT = 5

# Timeout (in seconds) for socket operations when fetching remote source files
SENTRY_SOURCE_FETCH_SOCKET_TIMEOUT = 2

# Maximum content length for source files before we abort fetching
SENTRY_SOURCE_FETCH_MAX_SIZE = 40 * 1024 * 1024
```

结合实际情况，我们排除由于 `SENTRY_SOURCE_FETCH_MAX_SIZE` 限制导致的请求文件失败问题。

### 修改 SENTRY_CACHE_MAX_VALUE_SIZE

在 `server.py` 内还存在 `SENTRY_CACHE_MAX_VALUE_SIZE` 来控制缓存的最大值，在查看之后，我们同样排除了该选项。

```python
# Maximum content length for cache value.  Currently used only to avoid
# pointless compression of sourcemaps and other release files because we
# silently fail to cache the compressed result anyway.  Defaults to None which
# disables the check and allows different backends for unlimited payload.
# e.g. memcached defaults to 1MB  = 1024 * 1024
SENTRY_CACHE_MAX_VALUE_SIZE = None
```

这里 `SENTRY_CACHE_MAX_VALUE_SIZE` 被设置为 None 以不限制其他缓存的阈值，即以各个缓存自身的配置为准。注意，这里**特别提到了 memcached 的默认值为 1MB.**

### memcached and memcache client

在前面我们提到，Sentry 会将拉取到的文件写入 memcached 内进行缓存，但是 memcached 每个 item 默认为 1MB，这似乎就是问题的症结所在。

在容器内我们对 memcached 服务配置进行查看，发现其 `item_size_max` 为 1048576（1MB）

```bash
$ memcached -h
memcached 1.6.10
-m, --memory-limit=<num>  item memory in megabytes (default: 64)
-I, --max-item-size=<num> adjusts max item size (default: 1m, min: 1k, max: 1024m)

$ echo 'stats settings' | nc localhost 11211 | grep 'max'
STAT maxbytes 67108864
STAT maxconns 1024
STAT item_size_max 1048576
```

这里我们将其默认值扩大为 10M，由于 memcached 不支持通过配置文件启动，因此我们需要在启动命令内添加配置，即：

```bash
memcached -I 10m
```

之后通过 `ps -ef | grep memcached` 来查看服务启动情况：

```bash
memcache      1      0  0 Aug03 pts/0    00:00:07 memcached -I 10m
```

接下来我们继续对 memcached-client 的配置进行升级，其参数配置为 `SERVER_MAX_VALUE_LENGTH`，通过查看源码，获取其默认值和修改配置的方法。

```python
# python3.6/site-packages
# Storing values larger than 1MB requires starting memcached with -I <size> for
# memcached >= 1.4.2 or recompiling for < 1.4.2. If you do, this value can be
# changed by doing "memcache.SERVER_MAX_VALUE_LENGTH = N" after importing this
# module.
SERVER_MAX_VALUE_LENGTH = 1024 * 1024
```

该配置值也没有暴露在配置文件内，因此我们需要在代码中修改，并重新打包、发布。

```python
# server.py snippet
import memcache
memcache.SERVER_MAX_VALUE_LENGTH = 10 * 1024 * 1024
```

## Relay response 400

部署上线之后，发现 sentry 服务的域名产生大量的 400 错误，通过查看 `relay` 日志，我们发现了一些异常，这里我们通过阅读源码对其表现和解决方案进行记录

Relay 返回 400 的场景

- 🐛 Too many envelopes (event_buffer_size reached)
- 🐛 invalid security report type
- 一些浏览器请求代理插件/扩展，会先触发一个 `Type=ping` 的请求，再发起真实请求，此时 ping 请求会返回 400
- 在 relay 的 envelope 接口内上报了自定义的字段，导致 relay 无法解析，详见[fix(server): Accept and forward unknown envelope items](https://github.com/getsentry/relay/pull/1246)

### Too many envelopes (event_buffer_size reached)

如果我们在服务上发现了大量的 400 状态码，通常是由该原因导致

```rust
[relay_server::endpoints::common] ERROR: error handling request: failed to queue envelope
caused by: Too many envelopes (event_buffer_size reached)
```

<HighlightWithText text="错误原因" />{' '}

当 `envelope` 处理对列堆积超过 [Config::event_buffer_size](https://docs.sentry.io/product/relay/options/)(默认为 1000) 时，会返回 400 错误。请求包含所有类型的 events、attachments 和 sessionsrelay。

#### 源码分析

通过分析 relay 源码，我们发现一些端倪：

`relay-server/src/actors/envelopes.rs`

```rust
// 如果缓冲区内堆积值超过设置阈值，返回错误和详情
if self.config.envelope_buffer_size() <= self.active_envelopes {
  return Err(QueueEnvelopeError::TooManyEnvelopes);
}

#[derive(Debug, Fail)]
pub enum QueueEnvelopeError {
  #[fail(display = "Too many envelopes (event_buffer_size reached)")]
  TooManyEnvelopes,
}
```

`relay-server/src/endpoints/common.rs`

```rs
// 定义错误信息
#[derive(Fail, Debug)]
pub enum BadStoreRequest {
  #[fail(display = "failed to queue envelope")]
  QueueFailed(#[cause] QueueEnvelopeError)
}

impl BadStoreRequest {
  fn to_outcome(&self) -> Option<Outcome> {
    Some(match self {
      BadStoreRequest::QueueFailed(event_error) => match event_error {
        QueueEnvelopeError::TooManyEnvelopes => Outcome::Invalid(DiscardReason::Internal),
      },
    })
  }
}
```

### invalid security report type

报错信息如下：

```
[relay_server::actors::envelopes] ERROR: failed to extract security report: invalid security report type
```

该问题相关 issues:

- [Rejected CSP reports from Firefox latest due to missing effective-directive payload](https://github.com/getsentry/sentry/issues/31433)
- [Too many 400 Bad Request](https://github.com/getsentry/relay/issues/1336)

<HighlightWithText text="错误原因" />{' '}

浏览器上报的数据类型未能被 sentry 识别，通常由 `session` 通道上报，因为使用的 **relay** 版本较低，在 22.7 之后的版本已经对其进行修复。

#### 源码分析

`relay-server/src/actors/envelopes.rs`

```rs
// 按照如下顺序从 envelope 内提取事件的 payload，事件仅从一个源内获取：
// 1. 显式事件，理解为通过 SDK 正常上报的事件；
// 2. 安全上报项，由浏览器根据安全策略上报；
// 3. Attachments `__sentry-event` and `__sentry-breadcrumb1/2`
// 4. 表单数据
fn extract_event(&self, state: &mut ProcessEnvelopeState) -> Result<(), ProcessingError> {
  if let Some(mut item) = raw_security_item {
      relay_log::trace!("processing security report");
      state.sample_rates = item.take_sample_rates();
      self.event_from_security_report(item).map_err(|error| {
          relay_log::error!("failed to extract security report: {}", LogError(&error));
          error
      })?
  }
}

// 定义错误信息
#[derive(Debug, Fail)]
enum ProcessingError {
  #[fail(display = "invalid security report type")]
  InvalidSecurityType
}

fn event_from_security_report(&self, item: Item) -> Result<ExtractedEvent, ProcessingError> {
    let len = item.len();
    let mut event = Event::default();

    let data = &item.payload();
    // 未能通过 payload 推断出其安全策略，直接返回错误
    let report_type = SecurityReportType::from_json(data)
        .map_err(ProcessingError::InvalidJson)?
        .ok_or(ProcessingError::InvalidSecurityType)?;

    let apply_result = match report_type {
        SecurityReportType::Csp => Csp::apply_to_event(data, &mut event),
        SecurityReportType::ExpectCt => ExpectCt::apply_to_event(data, &mut event),
        SecurityReportType::ExpectStaple => ExpectStaple::apply_to_event(data, &mut event),
        SecurityReportType::Hpkp => Hpkp::apply_to_event(data, &mut event),
    };

    if let Err(json_error) = apply_result {
        // logged in extract_event
        relay_log::configure_scope(|scope| {
            scope.set_extra("payload", String::from_utf8_lossy(data).into());
        });

        return Err(ProcessingError::InvalidSecurityReport(json_error));
    }
}
```

`relay-general/src/protocol/security_report.rs`

```rs
// 根据 paylod 来推断当前安全策略类型，如果没有匹配上，会直接返回错误
impl SecurityReportType {
  pub fn from_json(data: &[u8]) -> Result<Option<Self>, serde_json::Error> {
      #[derive(Deserialize)]
      #[serde(rename_all = "kebab-case")]
      struct SecurityReport {
          csp_report: Option<IgnoredAny>,
          known_pins: Option<IgnoredAny>,
          expect_staple_report: Option<IgnoredAny>,
          expect_ct_report: Option<IgnoredAny>,
      }

      let helper: SecurityReport = serde_json::from_slice(data)?;

      Ok(if helper.csp_report.is_some() {
          Some(SecurityReportType::Csp)
      } else if helper.known_pins.is_some() {
          Some(SecurityReportType::Hpkp)
      } else if helper.expect_staple_report.is_some() {
          Some(SecurityReportType::ExpectStaple)
      } else if helper.expect_ct_report.is_some() {
          Some(SecurityReportType::ExpectCt)
      } else {
          None
      })
  }
}
```

## Development

### 找不到 `performance` 入口

在本地部署 Sentry 后，发现找不到 performance 模块的入口

- 原因：Sentry v21.6.3 默认不支持 performance 特性，需要手动配置进行开启
- 解决：在 `~/.sentry/sentry.config.py` 内进行配置

参考[sentry.config.js](https://github.com/getsentry/self-hosted/blob/master/sentry/sentry.conf.example.py)

```python
SENTRY_FEATURES["organizations:performance-view"] = True
```

### invaild platform

在本地创建项目后，发现 `POST /api/0/teams/sentry/sentry/projects/` 报错 `400 invaild platform`

- 查看源码发现程序需要读取 `integration-docs` 目录下的文件，返回静态页面
- 通过执行 `sentry repair --with-docs` 拉取最新的集成列表，安装在本地的 sentry 内
